### ISSUE TITLE
Selenium driver version 2.43.1 does not run Firefox tests, version 2.46.0 fails walmart-shirt.js in firefox, passes in chrome

### ISSUE THREAD

**Issue by asunar** [TestArmada/magellan#1]
$> "./node_modules/.bin/magellan" --browser=firefox --bail_fast
Sauce configuration OK
Magellan-nightwatch test iterator found nightwatch configuration at: ./conf/nightwatch.json

Running 3 tests with 3 workers with firefox

--> Worker 3, mock port: 12006, running test: tests/walmart-shirt.js @firefox
--> Worker 2, mock port: 12003, running test: tests/walmart-book.js @firefox
--> Worker 1, mock port: 12000, running test: tests/github.js @firefox

Opens firefox browser, fails with the following error message:
'Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms........'

Updated configuration to use selenium driver 2.46.0 like this:
"server_path": "./node_modules/testarmada-magellan-nightwatch/node_modules/selenium-server/lib/runner/selenium-server-standalone-2.46.0.jar"

$> "./node_modules/.bin/magellan" --browser=firefox --bail_fast
Sauce configuration OK
Magellan-nightwatch test iterator found nightwatch configuration at: ./conf/nightwatch.json

Running 3 tests with 3 workers with firefox

--> Worker 1, mock port: 12000, running test: tests/github.js @firefox
--> Worker 2, mock port: 12003, running test: tests/walmart-book.js @firefox
--> Worker 3, mock port: 12006, running test: tests/walmart-shirt.js @firefox
(1 / 3) <-- Worker 1 PASS  tests/github.js @firefox
(2 / 3) <-- Worker 2 PASS  tests/walmart-book.js @firefox
(3 / 3) <-- Worker 3 FAIL  tests/walmart-shirt.js @firefox
.......
ERROR: Unable to locate element: "[data-magellan-temp-automation-id='magellan_click_6c0a5e2']" using: css selector
Unable to locate element: "[data-magellan-temp-automation-id='magellan_click_6c0a5e2']" using: css selector

FAILED:  1 errors and 1 passed (5.878s)

Running:  Check product details
 ✖ Selector '.product-short-description' was not visible after 60117 milliseconds.  - expected "visible" but got: not visible

-----------------------------------------

λ "./node_modules/.bin/magellan" --browser=chrome --bail_fast
Sauce configuration OK
Magellan-nightwatch test iterator found nightwatch configuration at: ./conf/nightwatch.json

Running 3 tests with 3 workers with chrome

--> Worker 3, mock port: 12006, running test: tests/walmart-shirt.js @chrome
--> Worker 2, mock port: 12003, running test: tests/walmart-book.js @chrome
--> Worker 1, mock port: 12000, running test: tests/github.js @chrome
(1 / 3) <-- Worker 2 PASS  tests/walmart-book.js @chrome
(2 / 3) <-- Worker 1 PASS  tests/github.js @chrome
(3 / 3) <-- Worker 3 PASS  tests/walmart-shirt.js @chrome

============= Suite Complete =============

     Status: PASSED
    Runtime: 27.8s
Total tests: 3
 Successful: 3 / 3

**Comment by Maciek416** [comment]
Confirmed. Looks like nightwatch is unable to click the product tile. We'll probably replace this with a friendlier test :)

**Comment by Maciek416** [comment]
We've removed this test for the moment. The tests aren't really intended to test `magellan` anyway :)

**Comment by Maciek416** [comment]
Note also: We're `2.46.0` updated across the board now.
