### ISSUE TITLE
Is there a way to pass arguments from the cli directly to the test suite?

### ISSUE THREAD

**Issue by kabirsikand** [TestArmada/magellan#123]
e.g. `magellan --[parameter_name]=[params]` or `magellan --parameters=[path/to/file.json]`

**Comment by kabirsikand** [comment]
I'd want to access these directly from my tests.

**Comment by Maciek416** [comment]
There isn't, but the environment (i.e. `process.env`) does make it from Magellan's parent process all the way down to child processes, and this is a way you can push information down to workers.

Some of our users use the `config` module's `NODE_CONFIG` environment variable and `NODE_ENV` feature (see: https://github.com/lorenwest/node-config/wiki/Environment-Variables ) to pass along balls of JSON to their workers. This has the added benefit of working nicely in CI environments that allow you to set up variants of environment variables per job

**Comment by kabirsikand** [comment]
@Maciek416 maybe we can open up a gitter chat channel for quick support Q's like this so we don't pollute the issues list?
