### ISSUE TITLE
Directly support the wdio test runner without mocha (plugin request)

### ISSUE THREAD

**Issue by kabirsikand** [TestArmada/magellan#124]
Enhancement/Feature: Can we support the [wdio](http://github.com/webdriverio/webdriverio) test runner @ v4? Would bring two of the best testing tools together.

**Comment by ryan-roemer** [comment]
This is already supported, with an example at: https://github.com/TestArmada/boilerplate-mocha-webdriverio

**Comment by Maciek416** [comment]
Please see the boilerplate example for webdriverio @ryan-roemer linked above. You should be able to keep up with new wdio versions as they come out as the coupling between magellan and the actual runner is very loose. (Let us know if you have issues though!)

**Comment by kabirsikand** [comment]
It still uses mocha to run the tests. WDIO has a test runner built into it, which dramatically changes the actual test suite implementation (synchronous commands vs async). I am requesting that the wdio runner be used instead of the mocha runner.

**Comment by kabirsikand** [comment]
@Maciek416

**Comment by Maciek416** [comment]
Ah, my bad! Re-opening

**Comment by Maciek416** [comment]
(edited the title to clarify)

**Comment by jackson-sandland** [comment]
Why is the webdriverIO example no longer available? Does Magellan recommend nightwatch over webdriverIO?
