### ISSUE TITLE
--group option not running the test in a folder

### ISSUE THREAD

**Issue by divyaguptatajawal** [TestArmada/magellan#154]
I tried using $./node_modules/.bin/magellan --group=tests/smoke but its running all the tests in the tests folder.
the structure of my project folder is  
  ├─┬  @tests
  │ ├── test3.js
  │ ├─┬ smoke
  │ │   └─┬ test1.js
  │ │   └── test2.js

Actual : all tests: test1.js, test2.js, test3.js are running, however the above command should run only test1.js and test2.js

**Comment by Maciek416** [comment]
Hey @divyaguptatajawal , please see https://github.com/TestArmada/magellan-nightwatch-plugin for the module that implements the `group` option. Since it's part of that module and not the magellan project itself, I'm closing this issue. Thanks for filing this.
