### ISSUE TITLE
Magellan requires sudo permission to run test cases

### ISSUE THREAD

**Issue by amitmawkin** [TestArmada/magellan#164]
If we dont run our test cases with higher privileges such as root , we keep keep getting these errors.

```
Magellan 8.8.4
Will try to load configuration from default of ./magellan.json
Loaded configuration from:   wip/workspace/automated-tests/magellan.json
Magellan is creating temporary files at: wip/workspace/automated-tests/temp
Sauce configuration OK
Magellan-nightwatch test iterator found nightwatch configuration at: ./conf/nightwatch.json
Scanning tests for test files ...
[32mFound 4 test files in tests[39m

Running 4 tests with 3 workers with phantomjs

Found selenium HTTP server at port 12000, port is in use.
Found selenium HTTP server at port 12003, port is in use.
Found selenium HTTP server at port 12006, port is in use.
Found selenium HTTP server at port 12001, port is in use.
Found selenium HTTP server at port 12004, port is in use.
Found selenium HTTP server at port 12007, port is in use.
Found selenium HTTP server at port 12002, port is in use.
[93mDetected port contention while spinning up worker: [39m
[93m  in use: #: 12000 purpose: mocking port[39m
[93m  in use: #: 12001 purpose: selenium port[39m
[93m  in use: #: 12002 purpose: generic[39m
Found selenium HTTP server at port 12008, port is in use.
[93mDetected port contention while spinning up worker: [39m
[93m  in use: #: 12006 purpose: mocking port[39m
[93m  in use: #: 12007 purpose: selenium port[39m
[93m  in use: #: 12008 purpose: generic[39m
Found selenium HTTP server at port 12005, port is in use.
[93mDetected port contention while spinning up worker: [39m
[93m  in use: #: 12003 purpose: mocking port[39m
[93m  in use: #: 12004 purpose: selenium port[39m
[93m  in use: #: 12005 purpose: generic[39m
Found selenium HTTP server at port 12012, port is in use.
Found selenium HTTP server at port 12009, port is in use.
Found selenium HTTP server at port 12015, port is in use.
Found selenium HTTP server at port 12013, port is in use.
Found selenium HTTP server at port 12010, port is in use.
Found selenium HTTP server at port 12016, port is in use.
Found selenium HTTP server at port 12011, port is in use.
[93mDetected port contention while spinning up worker: [39m
[93m  in use: #: 12009 purpose: mocking port[39m
[93m  in use: #: 12010 purpose: selenium port[39m
[93m  in use: #: 12011 purpose: ge
```

**Comment by amitmawkin** [comment]
any updates?

**Comment by Maciek416** [comment]
The errors you see above either suggest that processes (from previous runs) are being left behind or your user doesn't have the ability to use these ports. Nightwatch and selenium don't require root, and neither does magellan's own port utility, so I'm not sure what's going on here without more info.

**Comment by amitmawkin** [comment]
Thanks for responding, these are getting run as part of a jenkins build job . Jenkins is run as jenkins user. 
What more info would you need.

**Comment by geekdave** [comment]
@amitmawkin can you try logging into the jenkins box directly as the jenkins user, and using something like https://www.npmjs.com/package/http-server to try to start up a dummy server on port 12000 to see what happens?

**Comment by amitmawkin** [comment]
@geekdave yes I can install and run it under user jenkins
[jenkins@myjenkins automated-tests]$ ./node_modules/.bin/http-server -p 12000
Starting up http-server, serving ./
Available on:
  http://127.0.0.1:12000
  http://XXXXXXXXX:12000
Hit CTRL-C to stop the server

**Comment by Maciek416** [comment]
My best guess is that some part of the port checking code doesn't function the same on your Jenkins machine as elsewhere.

We need a smoking gun in the form of a specific line of code that's failing on your box.

We use the `portscanner` node module to scan for port availability ( see: https://github.com/TestArmada/magellan/blob/master/src/util/check_ports.js#L5 ) . Does this package work for scanning port `12000` on your Jenkins machine as non-root?

**Comment by amitmawkin** [comment]
Sorry @Maciek416 i was out, i ran the module, did not get any error message
