### ISSUE TITLE
remote testing without saucelabs

### ISSUE THREAD

**Issue by DeltaLikeM** [TestArmada/magellan#197]
We have a remote machine running with a selenium server and multiple browsers. I already set up magellan to test locally. Now I want to use it as part of my Jenkinsfile but I want to test against my remote selenium server is there a possibility ?

Thanks in advance

**Comment by archlichking** [comment]
@DeltaLikeM At this moment magellan doesn't support selenium grid unfortunately. But selenium grid as an important executing environment should be removed out from the big picture. We've released `magellan@10` recently. With the new architecture selenium grid support is totally doable via executor. Please hold on tight for our `magellan-selenium-grid-executor`.

**Comment by archlichking** [comment]
Hi @DeltaLikeM, we just released the beta version of https://www.npmjs.com/package/testarmada-magellan-seleniumgrid-executor. Please try it out and let us know what you feel.

**Comment by DeltaLikeM** [comment]
@archlichking sorry for this late response 
thank you very much for updating this issue.
