### ISSUE TITLE
Configuration for SauceLabs Emulators is limited

### ISSUE THREAD

**Issue by jtheodore-rent** [TestArmada/magellan#200]
Hey all,

I'm having another issue that I'm working through with Saucelabs support - when I use the emulators provided by the --list_browsers command, they are saying that I am using deprecated configuration settings.  Specifically, "platform: Linux" for my the Galaxy S4 emulator.

When I've tried to use the Android 5.1 emulator, it hasn't worked - any suggestions on how to get better or more accurate control of this?

**Comment by archlichking** [comment]
@jtheodore-rent can you give `magellan@10` a shot by the [migration guide](https://github.com/TestArmada/boilerplate-nightwatch/blob/master/migration.md)? We bump Guacamole to version 2 in `magellan-saucelabs-executor` there. Let us know how things work with `magellan@10`.

**Comment by archlichking** [comment]
@jtheodore-rent we just released `testarmada-magellan-saucelabs-executor@1.0.3`, which supports arbitrary customized flags for sauce connect. please refer to https://github.com/TestArmada/magellan-saucelabs-executor#customize-sauce-tunnel-flags
