### ISSUE TITLE
Running nightwatch tests with tags isn't working

### ISSUE THREAD

**Issue by jtheodore-rent** [TestArmada/magellan#201]
When I try to run tests with magellan using nightwatch tags, it doesn't work - I always get 'Error: no tests found'

My tests are tagged as described on the website:

Example:
module.exports = {
  '@tags': ['small'],

But when I attempt to run the following command, I get the error mentioned above:

magellan --tag=small

**Comment by archlichking** [comment]
@jtheodore-rent `testarmada-magellan-nightwatch-plugin` version 5 and below support 
```javascript
module.exports = {
tags: ['small'],
```

but not tags with `@tags`.  

However this is a valid feature request. We have both `@tags` and `tags` supported  `testarmada-magellan-nightwatch-plugin@6.0.2`. You'll need `magellan@10` for it, please follow https://github.com/TestArmada/boilerplate-nightwatch/blob/master/migration.md
