### ISSUE TITLE
Number of tests in JUnit reports is not correct. 

### ISSUE THREAD

**Issue by qacwnfq** [TestArmada/magellan#204]
When exposing the reports to the Jenkins JUnit plugin every successful test is counted once, independently of how many browsers it ran on. If however a test fails, for every browser the tests failed in one test failure is recorded (This is how I think it should be).
Is it possible to change the reporting on your end to count every successful test once for every browser it is run on?

Currently it looks like the number of tests changed when you fix test failures and this is miss leading!

**Comment by qacwnfq** [comment]
In the reports one can find:
```
 <testsuite name="test", package="", id, tests=8">
...
</testsuite>
```

How about appending the browser name to the test name? This way in Jenkins it also becomes clear which browser failed without having to look at the log.

**Comment by archlichking** [comment]
@qacwnfq are you referring to this repo https://github.com/TestArmada/magellan-xunit-reporter? if so please open issue there :)
