### ISSUE TITLE
Getting below error when executing nightwatch ui tests

### ISSUE THREAD

**Issue by amitmawkin** [TestArmada/magellan#211]
Getting this after I upgraded the framework to latest and greatest
`$ DPRO=local ./node_modules/.bin/magellan --local_browser chrome
[INFO] [Magellan] Magellan is creating temporary files at: /Users/xxxxx/dev/saranyu/temp
[INFO] [Magellan] Magellan 10.0.2
[INFO] [Magellan] Will try to load configuration from default of ./magellan.json
Loaded configuration from:  /Users/xxxxx/dev/saranyu/magellan.json
[INFO] [Magellan] Loaded test framework:
[INFO] [Magellan]   testarmada-magellan-nightwatch-plugin
[INFO] [Magellan] Loaded test executors:
[INFO] [Magellan]   testarmada-magellan-local-executor
[INFO] [Magellan Nightwatch Plugin] test iterator found nightwatch configuration at: ./nightwatch.json
[INFO] [Magellan Nightwatch Plugin] Scanning ui/tests/e2e for test files ...
[INFO] [Magellan Nightwatch Plugin] Found 1 test files in ui/tests/e2e
[INFO] [Magellan] Running 1 tests with 3 workers with [env:chrome|executor:local]
[INFO] [Magellan] --> Worker 1, mock port:12000, running test: ui/tests/e2e/saranyuhome.js @env:chrome|executor:local
/Users/xxxxxx/dev/saranyu/node_modules/testarmada-magellan/src/test_runner.js:390
      testMetadata.executor = test.executor.shortName;
                            ^

TypeError: Cannot set property 'executor' of undefined
    at ChildProcess.once (/Users/xxxxxx/dev/saranyu/node_modules/testarmada-magellan/src/test_runner.js:390:29)
    at ChildProcess.f (/Users/xxxxxx/dev/saranyu/node_modules/once/once.js:25:25)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)`

**Comment by archlichking** [comment]
@amitmawkin Thanks for the feedback. We'd already fixed the issue in 10.0.3 however there was a delay in publishing. `Magellan@10.0.3` is out with the fix at this moment. Please give it a shot.

**Comment by amitmawkin** [comment]
Thanks that fixes the above issue , but I am back to this one and do not remember how I resolved it in first place
`[INFO] [Magellan] Magellan is creating temporary files at: /Users/XXXXX/dev/saranyu/temp
[INFO] [Magellan] Magellan 10.0.3
[INFO] [Magellan] Will try to load configuration from default of ./magellan.json
Loaded configuration from:  /Users/XXXXXX/dev/saranyu/magellan.json
[INFO] [Magellan] Loaded test framework:
[INFO] [Magellan]   testarmada-magellan-nightwatch-plugin
[INFO] [Magellan] Loaded test executors:
[INFO] [Magellan]   testarmada-magellan-local-executor
[INFO] [Magellan Nightwatch Plugin] test iterator found nightwatch configuration at: ./nightwatch.json
[INFO] [Magellan Nightwatch Plugin] Scanning ui/tests/e2e for test files ...
[INFO] [Magellan Nightwatch Plugin] Found 1 test files in ui/tests/e2e
[INFO] [Magellan] Running 2 tests with 3 workers with [env:phantomjs|executor:local, env:chrome|executor:local]
[INFO] [Magellan] Found selenium HTTP server at port 12000, port is in use.
[INFO] [Magellan] Found selenium HTTP server at port 12003, port is in use.
[INFO] [Magellan] Found selenium HTTP server at port 12001, port is in use.
[INFO] [Magellan] Found selenium HTTP server at port 12004, port is in use.
[INFO] [Magellan] Found selenium HTTP server at port 12002, port is in use.
[WARN] [Magellan] Detected port contention while spinning up worker:
[WARN] [Magellan]   in use: #: 12000 purpose: mocking port
[WARN] [Magellan]   in use: #: 12001 purpose: selenium port
[WARN] [Magellan]   in use: #: 12002 purpose: generic
[INFO] [Magellan] Found selenium HTTP server at port 12005, port is in use.
[WARN] [Magellan] Detected port contention while spinning up worker:
[WARN] [Magellan]   in use: #: 12003 purpose: mocking port
[WARN] [Magellan]   in use: #: 12004 purpose: selenium port
[WARN] [Magellan]   in use: #: 12005 purpose: generic
[INFO] [Magellan] Found selenium HTTP server at port 12006, port is in use.
[INFO] [Magellan] Found selenium HTTP server at port 12009, port is in use.
[INFO] [Magellan] Found selenium HTTP server at port 12007, port is in use.
[INFO] [Magellan] Found selenium HTTP server at port 12010, port is in use.
[INFO] [Magellan] Found selenium HTTP server at port 12008, port is in use.`

**Comment by archlichking** [comment]
@amitmawkin make sure all testarmada dependencies are up-to-date and, make sure there isn't any zombie selenium/chrome/phantomjs process in the background holding those ports.
