### ISSUE TITLE
Platform names for Linux in magellan.json profiles

### ISSUE THREAD

**Issue by qacwnfq** [TestArmada/magellan#215]
I'm creating a test profile for sauce labs and I want to test browser on Linux.
I can't seem to guess the profile name for Linux from the examples for OSX and Windows.
I tried things like:
```

"browser": "firefox_latest_Linux"

"browser": "firefox_latest_Linux_Desktop"

"browser": "firefox_latest_Debian_8_Desktop"

"browser": "firefix_latest_Ubuntu_14_Desktop"
```

What would be the correct way to define a a browser using Linux as a platform?

**Comment by Maciek416** [comment]
Browser ids come from a translation of everything available in the Saucelabs browser list. Use Magellan's command line argument `--list_browsers` to see everything available in the current list. 

Note that the list can gradually shift over time as Saucelabs changes its own inventory of browsers, OS versions, etc.

For more information on how these ids are generated behind the scenes, check out our [guacamole](https://github.com/TestArmada/guacamole) project

**Comment by qacwnfq** [comment]
I found it thanks!
magellan --sauce_list_browsers did it for me.

**Comment by Maciek416** [comment]
@qacwnfq whoops, apologies, Magellan's been changin' lately :)
