### ISSUE TITLE
Changing Targeted nightwatch.json config file

### ISSUE THREAD

**Issue by joewdriver** [TestArmada/magellan#238]
Hi Again,

Not really an issue, but I'm unfamiliar with the git project tracker and not sure how to just submit a question.

If we'd like to point magellan to a different json file than nightwatch.json, where would we make that change?

Thanks for the help,

Joe

**Comment by archlichking** [comment]
you can use `--nightwatch_conf` which is defined in `magellan-nightwatch-plugin` https://github.com/TestArmada/magellan-nightwatch-plugin/blob/master/lib/help.js#L14
