### ISSUE TITLE
unknown error: cannot find Chrome binary

### ISSUE THREAD

**Issue by firstsko** [TestArmada/magellan#25]
centos 6.4
x64
java 1.7

{ [UnknownError: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281),platform=Linux 3.13.0-49-generic x86_64)]
  code: 13,
  state: 'unknown error',
  message: 'unknown error: cannot find Chrome binary\n  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281),platform=Linux 3.13.0-49-generic x86_64)',
  name: 'UnknownError',
  stack: 'UnknownError: unknown error: cannot find Chrome binary\n  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281),platform=Linux 3.13.0-49-generic x86_64)\n    at new bot.Error (/root/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)\n    at Object.bot.response.checkResponse (/root/node_modules/browsertime/node_modules/selenium-webdriver/lib/atoms/response.js:109:9)\n    at /root/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:160:24\n    at promise.ControlFlow.runInFrame_ (/root/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)\n    at goog.defineClass.notify (/root/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)\n    at promise.Promise.notify_ (/root/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)\n    at Array.forEach (native)\n    at promise.Promise.notifyAll_ (/root/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)\n    at goog.async.run.processWorkQueue (/root/node_modules/browsertime/node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)\n    at runMicrotasksCallback (node.js:337:7)\nFrom: Task: WebDriver.createSession()\n    at Function.webdriver.WebDriver.acquireSession_ (/root/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:157:22)\n    at Function.webdriver.WebDriver.createSession (/root/node_modules/browsertime/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:30)\n    at new Driver (/root/node_modules/browsertime/node_modules/selenium-webdriver/chrome.js:783:36)\n    at Builder.build (/root/node_modules/browsertime/node_modules/selenium-webdriver/builder.js:454:14)\n    at Object.module.exports.getDriver (/root/node_modules/browsertime/lib/browsers/chrome.js:41:49)\n    at /root/node_modules/browsertime/lib/browsertime.js:107:64\n    at /root/node_modules/browsertime/node_modules/async/lib/async.js:744:13\n    at /root/node_modules/browsertime/node_modules/async/lib/async.js:46:16\n    at /root/node_modules/browsertime/node_modules/async/lib/async.js:260:32\n    at /root/node_modules/browsertime/node_modules/async/lib/async.js:37:16' }
unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281),platform=Linux 3.13.0-49-generic x86_64)

**Comment by Maciek416** [comment]
Is this using one of the boilerplates?
