### ISSUE TITLE
Ubuntu 14.04 unknown error: cannot find Chrome binary

### ISSUE THREAD

**Issue by asunar** [TestArmada/magellan#3]
Ubuntu 14.04  Desktop
java version "1.7.0_79"
node version: v0.10.25
npm version: 2.13.3

./node_modules/.bin/magellan --serial --browser=chrome --bail_fast

Error retrieving a new session from the selenium server
{ status: 13,
  sessionId: null,
  value: 
   { supportUrl: null,
     additionalInformation: '\nDriver info: org.openqa.selenium.chrome.ChromeDriver',
     cause: null,
     systemInformation: 'System info: host: \'asunar-VirtualBox\', ip: \'127.0.1.1\', os.name: \'Linux\', os.arch: \'i386\', os.version: \'3.16.0-30-generic\', java.version: \'1.7.0_79\'',
     class: 'org.openqa.selenium.WebDriverException',
     suppressed: [ [length]: 0 ],
     hCode: 16165686,
     message: 'unknown error: cannot find Chrome binary\n  (Driver info: chromedriver=2.12.301324 (de8ab311bc9374d0ade71f7c167bad61848c7c48),platform=Linux 3.16.0-30-generic x86) (WARNING: The server did not provide any stacktrace information)\nCommand duration or timeout: 924 milliseconds\nBuild info: version: \'2.43.1\', revision: \'5163bce\', time: \'2014-09-10 16:27:33\'\nSystem info: host: \'asunar-VirtualBox\', ip: \'127.0.1.1\', os.name: \'Linux\', os.arch: \'i386\', os.version: \'3.16.0-30-generic\', java.version: \'1.7.0_79\'\nDriver info: org.openqa.selenium.chrome.ChromeDriver',
     buildInformation: 
      { releaseLabel: '2.43.1',
        buildTime: '2014-09-10 16:27:33',
        class: 'org.openqa.selenium.internal.BuildInfo',
        buildRevision: '5163bce',
        hCode: 33066190 },
     localizedMessage: 'unknown error: cannot find Chrome binary\n  (Driver info: chromedriver=2.12.301324 (de8ab311bc9374d0ade71f7c167bad61848c7c48),platform=Linux 3.16.0-30-generic x86) (WARNING: The server did not provide any stacktrace information)\nCommand duration or timeout: 924 milliseconds\nBuild info: version: \'2.43.1\', revision: \'5163bce\', time: \'2014-09-10 16:27:33\'\nSystem info: host: \'asunar-VirtualBox\', ip: \'127.0.1.1\', os.name: \'Linux\', os.arch: \'i386\', os.version: \'3.16.0-30-generic\', java.version: \'1.7.0_79\'\nDriver info: org.openqa.selenium.chrome.ChromeDriver' },
  state: 'unhandled error',
  class: 'org.openqa.selenium.remote.Response',
  hCode: 15619088 }

**Comment by geekdave** [comment]
Thanks for continuing to report back, @asunar - We're reserving some time tomorrow to tackle these issues.

**Comment by Maciek416** [comment]
Hey @asunar , can you grab the latest boilerplate, nuke your `node_modules`, and give this another try? 

We were woefully behind on `chromedriver` version (it was actually our own fork), and I was able to get similar problems in Ubuntu as you have. We've now updated to the latest and greatest public version.

**Comment by Maciek416** [comment]
@asunar also, if you'd prefer not to go from the boilerplate, simply update to `testarmada-magellan-nightwatch` version `1.4.23`. If you get an error about a missing selenium version, please make sure that your `nightwatch.json` matches the following path:

```
  "selenium": {
    "start_process": true,
    "server_path": "./node_modules/testarmada-magellan-nightwatch/node_modules/selenium-server/lib/runner/selenium-server-standalone-2.46.0.jar",
```

**Comment by Maciek416** [comment]
@asunar Closing this for now, let me know if it comes back after you try the latest (as described above).

**Comment by asunar** [comment]
Followed boilerplate instructions:
Before running npm test verified selenium.server_path in ./conf/nightwatch.json matches the path mentioned above.

In Windows 8.1 64 bit  the process hangs when I run npm test.

c:\code\myMagellanProject\automated-tests
λ npm test

> testarmada-boilerplate@1.1.1 test c:\code\myMagellanProject\automated-tests
> magellan

Sauce configuration OK
Magellan-nightwatch test iterator found nightwatch configuration at: ./conf/nightwatch.json

Running 3 tests with 3 workers with phantomjs

--> Worker 2, mock port: 12003, running test: tests/walmart-book.js @phantomjs
--> Worker 1, mock port: 12000, running test: tests/github.js @phantomjs
--> Worker 3, mock port: 12006, running test: tests/walmart-shirt.js @phantomjs

hangs....

I have an existing nightwatch test suite that I can run with phantomjs successfully as shown below
λ node nightwatch.js -t tests\login.js --testcase="Navigate to Forgot Password" -e phantomjs
Starting selenium server... started - PID:  14056

[Login] Test Suite
==================

Running:  Navigate to Forgot Password
 ✔ Testing if the URL equals ".../views/login/resetPassword.aspx".

OK. 1 assertions passed. (3.578s)

**Comment by asunar** [comment]
In Ubuntu 14.04 Desktop (via Virtual Box)
First time I ran npm test, it hanged.
Second time I ran npm test, first test failed the rest passed but it took about 6 mins.

Ubuntu in Virtual Box running on Windows is very slow I will post the actual output when I have some more time.

**Comment by asunar** [comment]
npm test hangs on Windows:  The sequel
http://screencast.com/t/FLh9UrIimBij 

Fix attempt (Feel free to fast forward :)
http://screencast.com/t/CBv2XTrMVN

Long path issues?
<img width="347" alt="longpath" src="https://cloud.githubusercontent.com/assets/204049/9129208/79fb89de-3c9a-11e5-8ecb-3d8d7d471faa.png">
