### ISSUE TITLE
Hosted Profile support

### ISSUE THREAD

**Issue by Maciek416** [TestArmada/magellan#30]
Right now profiles have to be in `magellan.json`, but it would be useful for an organization to be able to centralize profiles in one place, to avoid having to update dozens of files when transitioning to new tiers of browsers (or devices).

**Comment by mattfysh** [comment]
This is a great idea!

**Comment by Maciek416** [comment]
We need it pretty badly :)

We're currently managing these sorts of lists with Jenkins, but not all of our workflows go through Jenkins (eg: a local developer needing to preview the result of a suite locally with a given profile before sending it to a PR or CI).

**Comment by Maciek416** [comment]
Implemented and released
