### ISSUE TITLE
Tag-based filters don't support tests written in ES6

### ISSUE THREAD

**Issue by tildedave** [TestArmada/magellan#40]
I have magellan up and running against a non-trivial suite of nightwatch tests (written in ES6, using Nightwatch page objects, multiple environments).  This is pretty exciting!  I PRed some other issues I ran into that didn't seem to require any major design considerations but this one seems a bit bigger.

Acorn is used to parse test files and extract tags from them as static properties on the file.  This hardcodes Magellan to only support tests written in ES5 syntax.

I noticed that changing https://github.com/TestArmada/magellan/blob/master/src/test_filter.js#L42 from

```
    var root = acorn.parse(fs.readFileSync(path.resolve(f)));
```

to

```
    var root = acorn.parse(fs.readFileSync(path.resolve(f)), {
      ecmaVersion: 6
    });
```

fixes the issue but at the cost of potentially more confusion when a syntax error happens.  I think this might be the best solution as asking the consumer to opt-in to ES6 as part of their arguments to Magellan seems a bit unnecessary.

Any preference on how this issue might be fixed?

**Comment by Maciek416** [comment]
First of all, thanks for all the notes/issues. I hugely appreciate it!

As for my preference on how this issue could be fixed, I'm open to ideas! As you may have observed, tag support is still in what I'd call the "cheeseball phase" -- it's currently based purely on what `Nightwatch.js` likes to see ( `{ tags: [ "tag1", "tag2", "tag3" ] }` ). So for the long term, we need better ways of exposing tags and consuming tags. That may be for another day though.

In the meantime, I think maybe your fix is the right way to go. To mitigate syntax error confusion, we could just gobble up the error and output a helpful message of our own (to ease the literacy requirements on the consumer).

Thoughts?

**Comment by tildedave** [comment]
I'll PR that - thanks for the feedback!

**Comment by tildedave** [comment]
Added a pull request.  Biggest helpful thing I found that could be added was the filename in which there was a syntax error.  Let me know what else I can do here.
