### ISSUE TITLE
Unable to run tests on remote selenium grid

### ISSUE THREAD

**Issue by chrismikehogan** [TestArmada/magellan#54]
We have an internal selenium grid, and don't use SauceLabs. I'm having trouble getting magellan to run tests against our own grid. It is possible with nightwatch -- is it possible with magellan-nightwatch?

[The problem appears to be related to this bit](https://github.com/TestArmada/magellan/blob/64bc47a92b0e16b0ebae7ef262d74c870e8fcd52/src/interop/magellan-nightwatch/test_run.js#L22). Despite having configured nightwatch to send session requests to http://my-hub:4444, magellan is sending them to some port other than 4444.

Im basing this project off of the boilerplate-nightwatch.

My nightwatch.json https://gist.github.com/chrismikehogan/4defd025c5f8ac7b8dfb
My magellan.json https://gist.github.com/chrismikehogan/c2c6fc48af7cc48099bb
Example output:
```
[Github] Test Suite
===================

Running:  Load TestArmada GitHub page
INFO Request: POST http://my-hub:12001/wd/hub/session 
 - data:  {"desiredCapabilities":{"browserName":"chrome","javascriptEnabled":true,"acceptSslCerts":true,"platform":"ANY","name":"Github"}} 
 - headers:  {"Content-Type":"application/json; charset=utf-8","Content-Length":128}


Error retrieving a new session from the selenium server
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1000:19)


Connection refused! Is selenium server started?
```

**Comment by Maciek416** [comment]
The short answer to this is that we have never tested `magellan`'s parallelization capabilities via a `selenium-grid` installation :)

The longer answer is that for non-sauce (i.e. local) testing, `magellan` rewrites the selenium port that `nightwatch` uses with the expectation that `nightwatch` will start a local selenium server on that port, isolated from adjacent workers and allowed to crash without affecting those adjacent workers.

We haven't looked into selenium grid as it doesn't really fulfill the level of scaling we've needed for our testing efforts, so I can't say whether this is something we'll support, but if you want to attempt to hack your way around this to see what the results are like, I'm interested in hearing how it goes.

**Comment by chrismikehogan** [comment]
Thanks for the quick reply. If we get something interesting, I'll update here

**Comment by Maciek416** [comment]
Hey Chris, we've recently revisited this topic:

https://github.com/TestArmada/magellan-seleniumgrid-executor
