### ISSUE TITLE
Multi-file Tests Documentation

### ISSUE THREAD

**Issue by schneiderik** [TestArmada/magellan#62]
Other than the [comment in the webdriver.io boilerplate repo](https://github.com/TestArmada/boilerplate-mocha-webdriverio/blob/master/spec/inputs.js#L30-L31), I can't find a great deal of documentation around getting a multi-file test suite up and running.  Would you consider adding more documentation around it?

Specifically I am interested in a multi-file webdriver.io boilerplate.

Thanks!

**Comment by Maciek416** [comment]
@schneiderik merging a PR to address this ( https://github.com/TestArmada/boilerplate-mocha-webdriverio/pull/1 ) shortly. Hope you haven't been waiting too long!

**Comment by Maciek416** [comment]
Also, thanks for filing this ticket! This example was long overdue.

**Comment by schneiderik** [comment]
Thanks a ton!  We put some work in today and ended up coming up with almost exactly what was pull requested.

**Comment by Maciek416** [comment]
Great. Let me know if you have any other questions. I've also bumped that boilerplate to `2.0.2` in that PR.
