### ISSUE TITLE
Allow SauceLabs user Mocha's current test's name as the name of the current run.

### ISSUE THREAD

**Issue by kriuz** [TestArmada/magellan#66]
If for example, magellan is set up with rowdy to run tests with SauceLabs. Every test on SauceLabs will have the same name which can make it hard to tell what exactly is failing. It would be great if there was a way to pass the test name to SauceLabs.

**Comment by Maciek416** [comment]
Thanks for filing this. This one is important and is affecting some of our mocha-based test suites over at Walmart.

**Comment by Maciek416** [comment]
Adding notes from [Ryan's ticket](https://github.com/FormidableLabs/rowdy/pull/37#issuecomment-154222933)

```javascript
 sauceLabs: {
      default: {
        desiredCapabilities: {
          name: function () {
            return mocha.CURRENT_TEST_NAME;
          },
          tags: [SAUCE_TAG],
          public: "public",
          build: BUILD
        },
```
