### ISSUE TITLE
Add node API with global setup/teardown

### ISSUE THREAD

**Issue by jhudson8** [TestArmada/magellan#72]
Magellan is great but, if you run in parallel and want to start up a server, things get more difficult.  I'd love the ability to create a node file which would execute magellan using an API with a completion callback function.  Something like this

```
var magellan = require('testarmada-magellan');

magellan.start(magellanOptions, function (err) {
  // the magellan process should still exit just as it would have previously (with same error code)
  // but I could use this callback to tear down any services created for testing purposes
});
```

**Comment by Maciek416** [comment]
See #78
