### ISSUE TITLE
Feature Request: Reuse Sauce client environment.

### ISSUE THREAD

**Issue by ryan-roemer** [TestArmada/magellan#75]
Some environments are costly to the respective project to spin up. This could be lessened by allowing multiple tests to reuse a single Sauce VM environment.

Potential strawman:
- Require `--serial` for sanity is fine
- Allow a `--reuse-client` option to keep the existing Sauce / whatever environment
- Restart **all** the tests if any fail to make it simple.

This way, project owners can decide for themselves what is acceptable / too expensive to wait for in terms of Sauce VM startup time without having to completely give up slow starting Sauce VM environments.

**Comment by Maciek416** [comment]
Revisiting this issue so we can nudge it closer to reality:

While I'm fairly certain this notion breaks a couple of our core assumptions when it comes to `nightwatch`, I **believe** it could be made to work fairly naturally with `mocha`. Rough thoughts:

  - In `nightwatch`: the best I think we could do is synthesize a grouping (directories, tags) and use that as the test name.
  - In `mocha` we could simply iterate over `describe` blocks and use those strings as the "test name".
  - Still need to deeply examine any per-test actions that could happen in the interior of a `mocha` process that could violate something, but I **think** this should be ok. We haven't started adorning `mocha` tests with IPC or selenium session-nabbing code yet (as over in `nightwatch` land), so things are fairly easy to reason about.
