### ISSUE TITLE
Support local IE/Mac testing with VirtualBox

### ISSUE THREAD

**Issue by geekdave** [TestArmada/magellan#77]
For testing IE locally on a mac, would be great to be able to use:
- virtualbox to host a windows instance
- [ievms](https://github.com/xdissent/ievms) to obtain windows images from microsoft
- [iectrl](https://github.com/xdissent/iectrl) to auto-manage the images (handle re-installing after expiration, etc)

**Comment by Maciek416** [comment]
Is this possible with Nighwatch, wd, and webdriver.io?

**Comment by geekdave** [comment]
I _think_ it should be agnostic of those things, if we can figure out how to:

* use `iectrl` to send some remote commands to the VM to start the selenium server
* use `iectrl` to configure port forwarding between the VM and the mac host
* configure magellan to use `http://10.0.whatever` (the magic IP address of the virtualbox VM) as the selenium server

**Comment by Maciek416** [comment]
I would like to see us nudge forward on this one. Are there any more specifics we can identify on what to do / research / try / write next?
