### ISSUE TITLE
Look into `localtunnel` as SauceConnect alternative

### ISSUE THREAD

**Issue by geekdave** [TestArmada/magellan#81]
> [localtunnel](https://github.com/localtunnel/localtunnel) exposes your localhost to the world for easy testing and sharing! No need to mess with DNS or deploy just to have others test out your changes.

we could potentially look into using this instead of sauce connect, as it would allow a common solution across multiple BaaS providers

**Comment by Maciek416** [comment]
Nice idea! We should figure out a way to shape this into something that would power an official use case / demo / example.
