### ISSUE TITLE
Use local http server/sandbox for testing

### ISSUE THREAD

**Issue by geekdave** [TestArmada/magellan#83]
If google or wikipedia change their page or go down, our tests shouldn't fail.

Let's perhaps borrow the test playground from webdriver.io and spin it up as a localhost server during tests, and assert against that.

**Comment by Maciek416** [comment]
Magellan doesn't hit the network at all for its unit tests -- framework/SDK-level tests are mocked at the `magellan` project level, so this issue may be more appropriate for `magellan-nightwatch`

**Comment by geekdave** [comment]
I'm confused about https://github.com/TestArmada/magellan/pull/82/files#diff-f4d469031568ae06668457a52bc41085R9

**Comment by Maciek416** [comment]
Just a mock test. It is never run
